ALTER TABLE "csv_import_rows"
ADD COLUMN "instagram_handle" TEXT,
ADD COLUMN "instagram_url" TEXT,
ADD COLUMN "instagram_post_average_views" TEXT,
ADD COLUMN "instagram_reel_average_views" TEXT,
ADD COLUMN "instagram_story_7_day_average_views" TEXT,
ADD COLUMN "instagram_story_30_day_average_views" TEXT,
ADD COLUMN "instagram_engagement_rate" TEXT,
ADD COLUMN "instagram_followers" TEXT,
ADD COLUMN "tiktok_handle" TEXT,
ADD COLUMN "tiktok_url" TEXT,
ADD COLUMN "tiktok_average_views" TEXT,
ADD COLUMN "tiktok_engagement_rate" TEXT,
ADD COLUMN "tiktok_followers" TEXT,
ADD COLUMN "twitch_handle" TEXT,
ADD COLUMN "twitch_url" TEXT,
ADD COLUMN "twitch_average_views" TEXT,
ADD COLUMN "twitch_engagement_rate" TEXT,
ADD COLUMN "twitch_followers" TEXT,
ADD COLUMN "kick_handle" TEXT,
ADD COLUMN "kick_url" TEXT,
ADD COLUMN "kick_average_views" TEXT,
ADD COLUMN "kick_engagement_rate" TEXT,
ADD COLUMN "kick_followers" TEXT,
ADD COLUMN "x_handle" TEXT,
ADD COLUMN "x_url" TEXT,
ADD COLUMN "x_average_views" TEXT,
ADD COLUMN "x_engagement_rate" TEXT,
ADD COLUMN "x_followers" TEXT;

ALTER TABLE "channels"
ADD COLUMN "instagram_handle" TEXT,
ADD COLUMN "instagram_url" TEXT,
ADD COLUMN "tiktok_handle" TEXT,
ADD COLUMN "tiktok_url" TEXT,
ADD COLUMN "twitch_handle" TEXT,
ADD COLUMN "twitch_url" TEXT,
ADD COLUMN "kick_handle" TEXT,
ADD COLUMN "kick_url" TEXT,
ADD COLUMN "x_handle" TEXT,
ADD COLUMN "x_url" TEXT;

ALTER TABLE "channel_metrics"
ADD COLUMN "instagram_post_average_views" BIGINT,
ADD COLUMN "instagram_reel_average_views" BIGINT,
ADD COLUMN "instagram_story_7_day_average_views" BIGINT,
ADD COLUMN "instagram_story_30_day_average_views" BIGINT,
ADD COLUMN "instagram_engagement_rate" DOUBLE PRECISION,
ADD COLUMN "instagram_followers" BIGINT,
ADD COLUMN "tiktok_average_views" BIGINT,
ADD COLUMN "tiktok_engagement_rate" DOUBLE PRECISION,
ADD COLUMN "tiktok_followers" BIGINT,
ADD COLUMN "twitch_average_views" BIGINT,
ADD COLUMN "twitch_engagement_rate" DOUBLE PRECISION,
ADD COLUMN "twitch_followers" BIGINT,
ADD COLUMN "kick_average_views" BIGINT,
ADD COLUMN "kick_engagement_rate" DOUBLE PRECISION,
ADD COLUMN "kick_followers" BIGINT,
ADD COLUMN "x_average_views" BIGINT,
ADD COLUMN "x_engagement_rate" DOUBLE PRECISION,
ADD COLUMN "x_followers" BIGINT;
