export const JOB_NAMES = [
  "runs.discover",
  "runs.recompute",
  "runs.assess.channel-fit",
  "channels.enrich.llm",
  "channels.enrich.hypeauditor",
  "imports.csv.process",
  "exports.csv.generate",
  "hubspot-preview.enrich",
  "hubspot.import.batch",
  "hubspot.push.batch",
  "hubspot.health-check",
  "hubspot.object-sync.schedule",
  "hubspot.object-sync",
  "hubspot.webhook.process",
  "maintenance.refresh-stale",
] as const;
